### ISSUE TITLE
Nice project I hope I can colaborate with it

### ISSUE THREAD

**Issue by mingodad** [ipselon/react-ui-builder#1]
Hello !

I just found and started playing with this project through npm and also saw the videos at http://umyproto.com/ and found this empty repository here.

It seems that you plan to opensource it and be able to get feedback/help with it.

So far I saw it very interesting mainly by the possibility of create/reuse components.

Cheers !

**Comment by ipselon** [comment]
Hi, thank you.

I didn't figured out how to provide contribution to this project from others so far. But your feedback is welcome, fell free to write me directly.
