### ISSUE TITLE
host a demo

### ISSUE THREAD

**Issue by jeromeetienne** [ipselon/react-ui-builder#11]
to publish an online demo would help people trying it.

something which doesnt require local install before trying. 

just suggesting

**Comment by atleastimtrying** [comment]
+1

**Comment by peterps-health** [comment]
+1

**Comment by ipselon** [comment]
OK, I will find the way how to cut features of builder to be online and not to use server side.

**Comment by FoxxMD** [comment]
@ipselon You could use github pages as your host if you're worried about cost.

**Comment by jeromeetienne** [comment]
if server is in node.js, you can host it on nodejitsu for free (as your project is opensource)

just another possibility

**Comment by ipselon** [comment]
Well, the matter of cost is important too, but first of all there is some coupling with file generation - so, firstly I need to cut some functionality to make it work without file system accessing.

**Comment by shaunandrews** [comment]
At the very least a short video demo would go a long way.

**Comment by keithmancuso** [comment]
Agreed, even a video would be helpful for now, hard to justify downloading and installing without really knowing what it does?

**Comment by pleunv** [comment]
There's a video available here: https://www.youtube.com/watch?v=5nqOFSjXKPI

**Comment by ipselon** [comment]
Demo is available [here](http://umyproto.com/react-ui-builder/)
