### ISSUE TITLE
{"errno":-4058,"code":"ENOENT","path":"C:\\wamp\\www\\test-react"}

### ISSUE THREAD

**Issue by mr-lanholmes** [ipselon/react-ui-builder#12]
{"errno":-4058,"code":"ENOENT","path":"C:\\wamp\\www\\test-react"}

**Comment by mr-lanholmes** [comment]
For anyone that encounter this problem when cloning a project. You should create an empty dir first and use it.

**Comment by boossyad** [comment]
My divide no root
