### ISSUE TITLE
react-bootstrap and Material UI templates don't work on Chromium

### ISSUE THREAD

**Issue by arianvp** [ipselon/react-ui-builder#16]
I'm running Chromium 43.0.2357.132.  When I copy one of the templates the UI is uresponsive.  Non of the buttons work.

If I for example try to delete a component nothing happens and when I press the button again I get the following error in the console:
`Component with id 40 was not found`

**Comment by ipselon** [comment]
I tested builder just now on Chromium 46.0.2455.0, Mac OS X 10.10.4, node 0.12.7
It works as expected.

Please double check instruction to start working:
1. Install last version of node js
2. Install last version of builder as global
3. Start builder and go to address in the browser
4. Create an empty folder in which your account in OS can write
5. Clone project into this folder specifying absolute path to folder in OS

**Comment by stefanlegg** [comment]
I'm experiencing the same problem as @arianvp using the following:
* Chromium 43.0.2357.132
* Node 0.12.7
* OS X 10.11
* React UI Builder 2.11.3

**Comment by ipselon** [comment]
Could you try to use Chromium 46.0.2455.0 ? Is this OS in beta ?
BTW, react-ui-builder has only 0.2.7

**Comment by stefanlegg** [comment]
My apologies, copied over the wrong line! I'm using 0.2.7
I don't see a Chromium release for 46.x & on their calendar it looks like 46.x isn't set to release until August. Do you have a link?

**Comment by ipselon** [comment]
http://chromium.woolyss.com/download/#mac

**Comment by stefanlegg** [comment]
Thanks! 
One moment, I'll give it a try.

**Comment by stefanlegg** [comment]
Sorry, the UI is still unresponsive for me using 46.0.2455.0

**Comment by ipselon** [comment]
Do you have a chance to try builder on another OS X version - not beta ?

**Comment by stefanlegg** [comment]
Sure, no problem! I'll try on 10.10.4 now.

**Comment by ipselon** [comment]
Also take a look at Chromium console output if there is something...

**Comment by stefanlegg** [comment]
On the OS X 10.11 box the only error I see is:
`Uncaught TypeError: Cannot set property 'onComponentDidUpdate' of undefined (builder-bundle.js:55)`
Other than that there are just a few warnings.

Trying on 10.10.4 now.

**Comment by stefanlegg** [comment]
Same thing on OS X 10.10.4

**Comment by stefanlegg** [comment]
Guess this is the same issue as #13

**Comment by ipselon** [comment]
OK. Now I'm run out of ideas. I will try to localize the problem in the next release (very soon)  - if it still be present I'll be investigating further. So, now wait the next release.
Thank you for answers.

**Comment by ipselon** [comment]
Please update the builder and see if your problem is gone. If not - will investigate further.

**Comment by arianvp** [comment]
I've updated builder and updated chromium (to 43.0.2357.132) but still
```
Uncaught TypeError: Cannot set property 'onComponentDidUpdate' of undefined
```

**Comment by ipselon** [comment]
Still does't work ?

**Comment by bastiao** [comment]
No, it does not work. I'm at chrome, with OS X 10.10.3 (14D131).

**Comment by ipselon** [comment]
Please update to the last builder's version.

**Comment by bastiao** [comment]
React UI Builder(0.2.11) is that, right? It does not work.

**Comment by ipselon** [comment]
Yes, that's right. But I really couldn't reproduce this error, nor on OS X, neither on Windows. Something wrong with browser, I think.

**Comment by Hellblazer** [comment]
I'm having the same issue.  Up to date on os x, chrome and tried it out on the chromium link you indicated above.  Don't know if it helps, but here's the stack trace:

Uncaught TypeError: Cannot set property 'onComponentDidUpdate' of undefinedn.createClass.componentWillUnmount @ builder-bundle.js:56x.unmountComponent @ builder-bundle.js:46M.unmountComponent @ builder-bundle.js:29r.unmountChildren @ builder-bundle.js:77d.Mixin.unmountChildren @ builder-bundle.js:78M.Mixin.unmountComponent @ builder-bundle.js:31M.unmountComponent @ builder-bundle.js:29x.unmountComponent @ builder-bundle.js:46M.unmountComponent @ builder-bundle.js:29r.unmountChildren @ builder-bundle.js:77d.Mixin.unmountChildren @ builder-bundle.js:78M.Mixin.unmountComponent @ builder-bundle.js:31M.unmountComponent @ builder-bundle.js:29x.unmountComponent @ builder-bundle.js:46M.unmountComponent @ builder-bundle.js:29x.unmountComponent @ builder-bundle.js:46M.unmountComponent @ builder-bundle.js:29r.updateChildren @ builder-bundle.js:77d.Mixin._updateChildren @ builder-bundle.js:78d.Mixin.updateChildren @ builder-bundle.js:78M.Mixin._updateDOMChildren @ builder-bundle.js:31M.Mixin.updateComponent @ builder-bundle.js:31M.Mixin.receiveComponent @ builder-bundle.js:31M.receiveComponent @ builder-bundle.js:30x._updateRenderedComponent @ builder-bundle.js:46x._performComponentUpdate @ builder-bundle.js:46x.updateComponent @ builder-bundle.js:46M @ builder-bundle.js:29x.receiveComponent @ builder-bundle.js:46M.receiveComponent @ builder-bundle.js:30x._updateRenderedComponent @ builder-bundle.js:46x._performComponentUpdate @ builder-bundle.js:46x.updateComponent @ builder-bundle.js:46M @ builder-bundle.js:29x.performUpdateIfNecessary @ builder-bundle.js:46M.performUpdateIfNecessary @ builder-bundle.js:30r @ builder-bundle.js:7o.perform @ builder-bundle.js:30o.perform @ builder-bundle.js:30d.perform @ builder-bundle.js:7j @ builder-bundle.js:7M @ builder-bundle.js:29o.closeAll @ builder-bundle.js:30o.perform @ builder-bundle.js:30T.batchedUpdates @ builder-bundle.js:77g @ builder-bundle.js:7n @ builder-bundle.js:31c.enqueueSetState @ builder-bundle.js:31n.setState @ builder-bundle.js:46n.createClass.onModelChange @ builder-bundle.js:55A @ builder-bundle.js:45o.emit @ builder-bundle.js:79t.exports.trigger @ builder-bundle.js:45o.createStore.onGoToErrors @ builder-bundle.js:58(anonymous function) @ builder-bundle.js:59(anonymous function) @ builder-bundle.js:6j @ jquery-2.1.3.min.js:2k.fireWith @ jquery-2.1.3.min.js:2x @ jquery-2.1.3.min.js:4(anonymous function) @ jquery-2.1.3.min.js:4

**Comment by ipselon** [comment]
Yeah, thanks, I pretty sure that this is the same issue as here #37

**Comment by Hellblazer** [comment]
Ah, cool.  thanks!
