### ISSUE TITLE
Module not found: Error: Cannot resolve module '.builder\\src\\PageForDesk.js

### ISSUE THREAD

**Issue by luisrudge** [ipselon/react-ui-builder#17]
```
[["multi main","Module not found: Error: Cannot resolve module '.builder\\src\\PageForDesk.js' in c:\\bb","resolve module .builder\\src\\PageForDesk.js
in c:\\bb"," looking for modules in c:\\bb\\node_modules"," c:\\bb\\node_modules\\.builder doesn't exist (module as directory)","[c:\\bb\\node_modules\\.builder]"," @ multi main"]]
```

![image](https://cloud.githubusercontent.com/assets/941075/8667313/44be1396-29d4-11e5-9c3e-269ab74995f6.png)

**Comment by ipselon** [comment]
Please tell what project did you clone, and node version you are using.

**Comment by luisrudge** [comment]
I tried both bootstrap and material projects.

```
C:\Users\luis
λ node -v
v0.12.4

C:\Users\luis
λ npm -v
2.10.1
```

**Comment by mmeyer** [comment]
Had the same error message when I wanted to open in react-ui-builder a cloned published project. Problem did get resolved when I provided in the "Local project directory path" field the absolute path to the cloned project and not just a relative path, which caused the mentioned "Module not found: Error: Cannot resolve module '.builder\\src\\PageForDesk.js" error message. Maybe a hint in the description will help others not to run into the same problem.

**Comment by ipselon** [comment]
Thank you a lot. I missed fixing details of Usage chapter in Readme on GitHub.
Now I fixed it.
