### ISSUE TITLE
"Project has broken components-index.js file" "Object #<Object> has no method 'isAbsolute'"

### ISSUE THREAD

**Issue by jjk3** [ipselon/react-ui-builder#19]
I tried to clone the rgb selector project

"Project has broken components-index.js file"
"Object #<Object> has no method 'isAbsolute'"

**Comment by ipselon** [comment]
There is a problem with old versions of node.js in fs library.

Please update node.js to the current version.

**Comment by jjk3** [comment]
thanks will give that a go.
