### ISSUE TITLE
support for using proxy servers in builder

### ISSUE THREAD

**Issue by mhnatiuk** [ipselon/react-ui-builder#21]
I'm behind a corporate proxy, builder has no connection to the internet despite the fact that my browser has proper proxy settings.

**Comment by ipselon** [comment]
Builder is an http server which is listening to port 2222 and which makes connections to the interner. But, what kind of connection did you mean: connection to the gallery or through the proxy inside of the builder ?

**Comment by ipselon** [comment]
Did you solve your issue ?

**Comment by mhnatiuk** [comment]
Hey,
I haven't. I can only test it using my corporate proxy, which I'm able to test today.

below is the screen shot of the error
![image](https://cloud.githubusercontent.com/assets/2299492/8773421/79dd5208-2ed4-11e5-9914-adfcb5e8f6d7.png)

**Comment by ipselon** [comment]
OK, I think this is not an issue of the builder, but mostly of environment in your network.
