### ISSUE TITLE
React-ui-builder internal server error 

### ISSUE THREAD

**Issue by mhnatiuk** [ipselon/react-ui-builder#27]
When trying to clone the "Start with react-bootstrap"
On Chrome-43.0.2357.134 m on windows 7 enterprise
From chrome console:
Failed to load resource: net::ERR_EMPTY_RESPONSE
From web ui:
"Internal Server Error: error"

**Comment by ipselon** [comment]
It seems you have some issues with network stuff. Check if server is running on 2222 port, or you have rigths to reach it, or event to start something on local host.
