### ISSUE TITLE
Not valid ast?

### ISSUE THREAD

**Issue by ipselon** [ipselon/react-ui-builder#30]
![img_21072015_221734](https://cloud.githubusercontent.com/assets/11865795/8812804/f8adfc26-3006-11e5-82f8-28feadee35b2.png)

**Comment by ipselon** [comment]
Update version up to 0.2.10

**Comment by bastiao** [comment]
I tested in 0.2.10 and I still have the issue :( anyone else?

**Comment by ipselon** [comment]
Fixed it. Apparently babel-core version 5.7.4 was with bug in windows environment.

**Comment by ipselon** [comment]
Just update builder up to 0.2.11
