### ISSUE TITLE
Error: Cannot resolve module PageForDesk.js

### ISSUE THREAD

**Issue by thos37** [ipselon/react-ui-builder#33]
When I attempt to clone the bootstrap samples, I get the following error:

![screen shot 2015-07-27 at 8 35 13 am](https://cloud.githubusercontent.com/assets/621286/8910334/fafc19f8-343a-11e5-88b6-9b99a9359ec5.png)

**Comment by ipselon** [comment]
Could you please clone ones again, or just reinstall the builder ? If this will not remove error, tell me.

**Comment by DefiantBidet** [comment]
trying to get the material design samples; I get the same error.   
removed node_modules and tried again... no go.
uninstalled/re-installed the builder.... no go. 
```
[["multi main","Module not found: Error: Cannot resolve module 'material-clone/.builder/src/PageForDesk.js' in [path redacted],"resolve module material-clone/.builder/src/PageForDesk.js in [path redacted]"," @ multi main"]]
```

**Comment by ipselon** [comment]
Did you enter absolute path to folder where you cloned project ?

**Comment by DefiantBidet** [comment]
the [path redacted] displayed the absolute system path to my directory i'm trying to put all this in, if that's what you're asking me. 

i've done the following:
 - cloned existing project -> selected material design
 - entered absolute path/entered relative path from where the ui-builder is running (i.e. `./<path>`)

i get the following
relative path (error above)
absolute path ( working.)

ok so my bad. sorry :) thanks for the help

**Comment by ipselon** [comment]
You are welcome! :-)

**Comment by ipselon** [comment]
@thos37 Could you try to use absolute path while cloning the project ?

**Comment by DefiantBidet** [comment]
to be clear.... the path i used was literally `/Users/<userName>/<path/to/where/i/code/shite/>
and not `~/<path/to/where/i/code/shite/>` the former worked the latter did not (odd) ... in any event the screenie above seems to be a relative path to `test2` as opposed to (and i'm seriously guessing/paraphrasing here) `/Users/thos37/path_to_react-ui-builder_codebase`

**Comment by thos37** [comment]
Yes, global paths work.
