### ISSUE TITLE
How to add Collapse component from react js into component-index.js

### ISSUE THREAD

**Issue by phucpnt** [ipselon/react-ui-builder#35]
Hello
Thx for great tools you guys have built.

I would like to use the [Collapse](http://react-bootstrap.github.io/components.html#utilities-collapse) component from react bootstrap.
How should I implement it?

Regards
Phuc

**Comment by ipselon** [comment]
Hi, thank you.

I updated 'Start with react-bootstrap' project in the gallery. Please find 'CollapseButton' component in Enhanced group.

Regards

**Comment by ipselon** [comment]
@phucpnt did you try CollapseButton component ? does it fit your needs ?

**Comment by phucpnt** [comment]
@ipselon Nice
I has try the new CollapseButton, it fits my needs. I need to update it a bit btw.
I also understand more on how to add new component base on your updates.

Thanks very much
Regards

**Comment by ipselon** [comment]
You are welcome.
