### ISSUE TITLE
Bootstrap Builder

### ISSUE THREAD

**Issue by Immortalin** [ipselon/react-ui-builder#40]
Hi, is there any plans to open source the bootstrap builder?

**Comment by ipselon** [comment]
Unfortunately, this tool is not supported any more, and in order to prepare it for open source I have to spend a significant amount of time. Now I'm really busy with React UI Builder and finding funds to support it.

**Comment by Immortalin** [comment]
Isn't it a mostly client side tool, can't you just release the source code or do a kickstarter etc.?

**Comment by ipselon** [comment]
I can't do a kickstarter for any project, because I'm a resident of Ukraine. To ask someone to do that instead of me will take a lot of time.

Source code of Bootstrap Builder is tightly integrated with server Java code, and to open it I need make preparations: database schema, deployment scripts, etc. This is time consuming anyway.

**Comment by Immortalin** [comment]
I see.

**Comment by ipselon** [comment]
Why do you need Bootstrap Builder ? React UI Builder is created with the same idea and even has more sophisticated user interface, has more features and even has components - like Material UI. 
React builder can create static site as well as Bootstrap builder, even better because of ReactJS components dynamic.

**Comment by Immortalin** [comment]
I am not doing any react-based development. My main reason for using bootstrap builder is because I prefer GUI builders over writing code as I find writing front-end code to be too tedious.

**Comment by ipselon** [comment]
I see, sorry for that. But at first I need to raise some money.

**Comment by Immortalin** [comment]
@ipselon no problem. Thanks for all the effort that you have put into this anyway. I will support your patreon once I am able to.

**Comment by ipselon** [comment]
Many thanks. We will develop amazing product, stay in touch. And think of ReactJS - it's worth to use it for Web UI.

**Comment by Immortalin** [comment]
Hi, I am getting this error while installing:

```
> ws@0.5.0 install /home/immortalin/npm-global/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/immortalin/npm-global/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/immortalin/npm-global/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
npm WARN peerDependencies The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> ws@0.4.31 install /home/immortalin/npm-global/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/immortalin/npm-global/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/immortalin/npm-global/lib/node_modules/react-ui-builder/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm WARN optional dep failed, continuing fsevents@0.3.8
npm ERR! Linux 3.16.0-49-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "react-ui-builder" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for /tmp/npm-10413-225f6711/registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz
npm ERR! Expected: da42f49740c0b42db2ca9728571cb190c98efea3
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/immortalin/npm-debug.log
```

**Comment by ipselon** [comment]
I think this is issue with npm and node. Did you try to install something else from npm in global scope ?

**Comment by Immortalin** [comment]
Yup, installing jshint worked perfectly

**Comment by ipselon** [comment]
I'm not Linux user and not sure about it's guts, but I think that following looks bad:
```
npm ERR! shasum check failed for /tmp/npm-10413-225f6711/registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz
npm ERR! Expected: da42f49740c0b42db2ca9728571cb190c98efea3
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz
```

**Comment by ipselon** [comment]
have you install react-ui-builder before ?

**Comment by ipselon** [comment]
try to uninstall with -g option
and install it again
