### ISSUE TITLE
ENOENT error on windows trying to open local project folder

### ISSUE THREAD

**Issue by dpastoor** [ipselon/react-ui-builder#5]
```
{"errno":-4058,"code":"ENOENT","syscall":"lstat","path":"C:\\Users\\devin\\Documents\\Repos\\.builder"}
```

Also, not sure if the folder icon is supposed to be clickable 
![image](https://cloud.githubusercontent.com/assets/3196313/8081906/ef024fc8-0f46-11e5-975d-2e93572217bf.png)

however doesn't do anything when I click on it (would expect it to open a explorer window to choose a folder).

**Comment by ipselon** [comment]
Try to install the last version of node.js 

As for folder icon - this is more for "good looking" purposes, but further I think we will add file browser, and it is not in high priorty so far...

**Comment by ipselon** [comment]
@dpastoor does my comment help ?

**Comment by dpastoor** [comment]
Hi @ipselon I haven't tried yet, but I'm running 0.12.3 so unless between 0.12.3 --> 0.12.4 something major changed I don't think that would be the cause. I can try on 0.12.4 if you think that could be it - else any other ideas?

**Comment by ipselon** [comment]
There were already multiple cases similar to yours, so I can say this is the only cause of the problem.

**Comment by dpastoor** [comment]
gotcha I will update and cross my fingers and see if it works

**Comment by ipselon** [comment]
@dpastoor did you manage to open project ?
