### ISSUE TITLE
"Project has broken components-index.js file"

### ISSUE THREAD

**Issue by bachirelkhoury** [ipselon/react-ui-builder#6]
Interesting project. Eager to try it out but I'm getting this error for whatever template project I use "Start with react-bootstrap" or "Start with Material UI"

![screen shot 2015-06-13 at 7 06 11 pm](https://cloud.githubusercontent.com/assets/186698/8143758/889da28a-11ff-11e5-93ba-d465864f87cb.png)

**Comment by bachirelkhoury** [comment]
Upgraded npm, cleaned cache and reinstalled and problem is gone.
thanks

**Comment by tnrich** [comment]
I'm also getting this problem but don't want to upgrade node/npm..

Any thoughts?

**Comment by rm3nchaca** [comment]
which version of node/npm are you using? I have same problem on node v0.12.7 npm 2.11.3

**Comment by bachirelkhoury** [comment]
Mine still works with 
- react-ui-builder 0.2.5
- node 0.12.4
- npm 2.10.1
if I upgrade to latest it will probably break again.

**Comment by ipselon** [comment]
@bachirelkhoury you are missing bug fixes and quick style editing panel :-)
