### ISSUE TITLE
ENOENT on Linux

### ISSUE THREAD

**Issue by amftri** [ipselon/react-ui-builder#7]
Hi, I get

`{"errno":34,"code":"ENOENT","path":"/tmp/.builder"}`

When trying to open _any_ path, even 0777 ones line /tmp. Running the latest npm install of react-ui-builder, Ubuntu 15.04, node 0.10.38.

**Comment by ipselon** [comment]
Try install the latest node.js

**Comment by amftri** [comment]
That fixed it. :) Thanks for the ultra-fast reply!
