### ISSUE TITLE
.builder/src/PageForDesk.js Line 49: Unexpected token <

### ISSUE THREAD

**Issue by timsim00** [ipselon/react-ui-builder#8]
Worked through some issues to get cloning to work.  But now getting this error in terminal.  The builder loads with builder menus and buttons on the outer edges of the project work area, but the project work area itself is blank.  This is the bootstrap project that I cloned.  PageForDesk.js is 4 bytes long with only the word "null" in the file.  The error is on line 46 of react-ui-builder/templates/app/_page_js.tpl.  React transformer doesn't know to render it.  Maybe a missing type="text/jsx" is the issue?

**Comment by ipselon** [comment]
Could you please provide here a console output after project is loaded ?

**Comment by ipselon** [comment]
BTW, this happens when you have a component tag on the page which is not a React component (this can happen when you delete manually component reference from component-index.js file but left its tag on a page). So, I advise you to create a new page and delete others.

**Comment by timsim00** [comment]
This is the UI console when project is loaded:

CollapsableNav is deprecated. Use CollapsibleNav instead.
builder-bundle.js:31 You can read more about it here https://github.com/react-bootstrap/react-bootstrap/issues/425#issuecomment-97110963

I was thinking maybe the issue is related to this: http://stackoverflow.com/questions/28100644/reactjs-uncaught-syntaxerror-unexpected-token

Adding a page doesn't help as the work area is disabled.  Selecting a component shows the 'Clear clipboard' <button> at the top of the page, but nothing shows in the work area.  'Select a variant' also shows nothing in its work area.  Looks like I have to resolve the main issue first.

**Comment by ipselon** [comment]
Did you create any new components after project cloning ? Or you had this error right after project cloned and compiled ?

**Comment by timsim00** [comment]
This is error showed up immediately after cloning and loading the project.  I'm not able to create new components or anything.  The work area is inoperable.

**Comment by ipselon** [comment]
In that case I can suggest that you already have webpack installed with jsx loader. So, it might be helpful if you update webpack (maybe globally) and jsx loader.
In future version builder will use babel instead of jsx-loader...

**Comment by timsim00** [comment]
I installed webpack and jsx-loader globally, cleared cache, deleted projected, re-cloned...still getting same issue.

**Comment by ipselon** [comment]
Could you try to uninstall webpack and loader ? and then open the project...

**Comment by timsim00** [comment]
Uninstall globally or from within react-ui-builder?

**Comment by ipselon** [comment]
globally, not from builder

**Comment by timsim00** [comment]
Uninstall globally and reloaded project. Same issue.

**Comment by timsim00** [comment]
For some reason jsx doesn't know it's supposed to transform _page_js.tpl.  The error is hitting on the first line that needs to be transformed:

(<h4 style={{textAlign: 'center'}}>There are runtime errors during rendering of the page. Please see console output. React doesn't handle runtime errors.</h4>);

**Comment by ipselon** [comment]
_page_js.tpl - is just a template, it shoudn't be processed by webpack.

I need to emulate your environment. Please provide OS and node.js version.

**Comment by timsim00** [comment]
Had to update to latest version of node: 0.12.4  OSX is 10.9.5

**Comment by timsim00** [comment]
Right, I'm not saying that webpack is processing the template per se, just that the code in the template isn't being processed wherever it's pulled in.

**Comment by ipselon** [comment]
Hi @timsim00 
I found the problem, there is an issue with the latest [esformatter](https://www.npmjs.com/package/esformatter) version.
Please reinstall (unistall & install) react-ui-builder. 

Additionally there is new feature: breadcrumbs in toolbar to select component quickly without switching hierarchy view.

Enjoy.

**Comment by timsim00** [comment]
Success!  Thank you.
