### ISSUE TITLE
Cloned projects dont display ? 

### ISSUE THREAD

**Issue by ganarajpr** [ipselon/react-ui-builder#9]
Hi,

So I tried react-ui-builder by cloning this project and it doesnt seem to be working properly. Am I missing anything here ? 

Also I noticed that this codebase has package version 0.2.4 while the one in npm has 0.2.6 ? So is this outdated ?

**Comment by ipselon** [comment]
Hi,

Builder is compiled and assembled into __build__ folder. Find there react-ui-builder.js file and run it in node.js

**Comment by ganarajpr** [comment]
That is how I did it. The builder loads up perfectly fine. But when you provide the folder and clone bootstrap or material design project into it, the npm install happens perfectly fine. But the editor doesnt show the page ( with the buttons and all other components ) .. If I load up the same folder in react-ui-builder that is loaded from the 'npm install react-ui-builder -g ' version I can see the editor loading up. So it looks like there is a minor difference between the two things . 

This is the error that comes up when I run from the cloned project.
```
/home/ganaraj/Documents/bstrap/.builder/src/PageForDesk.js
Line 49: Unexpected token <
```

**Comment by ipselon** [comment]
This is not outdated.
But the reason of the error you have is in esformatter and esformatter-jsx versions.

Please double check that you have in npm_modules folder (which is in build folder) proper versions: 
    "esformatter": "0.6.1",
    "esformatter-jsx": "1.0.8"

in the next release packages will be updated, but now you have to use these ones.

**Comment by ganarajpr** [comment]
Hi,

Yeah. You are right. I had 
```
"esformatter-jsx": "^1.0.8"
```
and changing that to 
```
"esformatter-jsx": "1.0.8"
```
solved the problem for me.  Thanks for getting on top of this soo fast :)
